version: 2
jobs:
  pr_check:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3 
      - image: circleci/mysql:8.0.3
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Run test
          command: npm run ci:test

  build:
    docker:
      - image: circleci/node:10.16.3 
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: npm-start
          command: npm start

workflows:
  version: 2
  pr_check_test:
    jobs:
       - pr_check
  # build_and_deploy:
  #   jobs:
  #     - build